---
- name: Install epel-release
  yum:
    name: epel-release

- name: Install python-pip
  yum:
    name: python-pip

- name: Install docker python package
  pip:
    name: docker

- name: Create NEXUS Data directory
  file:
    path: "{{ nexus3_repository_data_directory }}"
    state: directory
    mode: 0755
    owner: 200

- name: Create NEXUS plugin directory
  file:
    path: "{{ nexus3_repository_plugin_directory }}"
    state: directory
    mode: 0755
    owner: 200

- name: upload HELM plugin
  copy:
    src: "files/nexus-repository-helm-0.0.7.jar"
    dest: "{{ nexus3_repository_plugin_directory }}/nexus-repository-helm-0.0.7.jar"
    owner: 200
  when: install_helm_plugin | default(true) | bool

- name: Create NEXUS container
  docker_container:
    image: "{{ nexus3_repository_container_image }}"
    name: "{{ nexus3_repository_container_name }}"
    state: started
    recreate: yes    
    volumes:
      - "{{ nexus3_repository_data_directory }}:/nexus-data"
      - "{{ nexus3_repository_plugin_directory }}:/opt/sonatype/nexus/deploy"
    published_ports:
      - "5000:5000"
      - "8081:8081"

- name: Create service file
  template:
    src: "templates/docker.service.j2"
    dest: "/lib/systemd/system/{{ nexus3_repository_container_name }}.service"
    mode: 644
  notify:
    - reload systemctl

- name: Enable service
  service:
      name: "{{ nexus3_repository_container_name }}"
      enabled: yes