---
- name: Install nexus
  include_tasks: install_nexus.yml
  when: nexus3_repository_install_nexus


- name: Configure nexus
  include_tasks: config_nexus.yml
  when: nexus3_repository_config_nexus
